version: 0.2

# FROM BUILD Specifying docker version in buildspec is deprecated. Using docker 19.03.1 .
phases:
  install:
    runtime-versions:
      docker: 18
  # pre_build:
  #   commands:
  #     - echo Logging in to Amazon ECR...
  #     - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...     
      # Passing eviroment variables to image. Maybe it is not secure.     
      - "docker build -t jobparser \
          --build-arg JP_DB_USERNAME=$JP_DB_USERNAME \
          --build-arg JP_DB_PASSWORD=$JP_DB_PASSWORD \
          --build-arg JP_DB_HOST=$JP_DB_HOST \
          --build-arg JP_DB_PORT=$JP_DB_PORT \
          --build-arg JP_DB_DBNAME=$JP_DB_DBNAME \
          --build-arg TELEGRAM_TOKEN=$TELEGRAM_TOKEN ."
      # - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      # todo made push to ECR
      - echo Build completed on `date`
      - docker run -d --name cname jobparser
      # increase test time for more reliability.
      - sleep 30
      - docker logs cname
      - docker stop cname
      # - echo Pushing the Docker image...
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Preparing archive for the Lambda function
      # - cd my-telegram-bot



      - cd ./my-telegram-bot
      - mv packages/* ./
      - zip -r /function.zip *

      - echo Updating Lambda function   
      - aws lambda update-function-code --function-name  my-telegram-bot-dev-hello   --zip-file  function.zip

artifacts:
  files:
    - '**/*'
  # discard-paths: yes
  # base-directory: './'
  secondary-artifacts:
      MyArtifactidentifier:
        files:
          - '/*'
        # discard-paths: yes
  # these artifacts are not used anywhere
  bot-artifacts:
      MyArtifactidentifier:
        files:
          - 'my-telegram-bot/**/*'
        # discard-paths: yes
